name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - uses: gradle/gradle-build-action@v2
      id: setup-gradle
      with:
        cache-disabled: true
        gradle-version: current
    - run: ./gradlew clean build --no-build-cache
