name: Build Gradle project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Gradle
    - uses: gradle/gradle-build-action@v2
      id: setup-gradle
      with:
        cache-disabled: true
        gradle-version: current
    - run: ./gradlew clean build --no-build-cache

  deploy:
    runs-on: windows-latest
    needs: build-gradle-project
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'API-trekker'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
          package: '*.jar'